blank_issues_enabled: false
contact_links:
  - name: Discussion Forum
    url: https://github.com/shawn-makes-stuff/PiggieSlicer/discussions
    about: Please raise ideas, feature suggestions, and support questions here.
